directories:
  output: ../../../bin/Desktop
  buildResources: ../../../build
appId: com.dsweb_electron6.app
productName: dsweb_electron6
copyright: Copyright © 2019
buildVersion: 1.0.0
compression: maximum
extraResources:
  - from: ./bin
    to: bin
    filter:
      - '**/*'
files:
  - from: ./ElectronHostHook/node_modules
    to: ElectronHostHook/node_modules
    filter:
      - '**/*'
  - filter:
      - '**/*'
electronVersion: 5.0.6
